#!/bin/bash

# Directory where Eclipse MAT is installed
MAT_DIR=~/mat

# Figure out where the Scala framework is installed
FWDIR="$(cd `dirname $0`; pwd)"

OUT_FILE="/tmp/estimate.out"
ERR_FILE="/tmp/estimate.err"

if [[ $# -ne 2 ]];
then
  echo "Usage $FWDIR/run_size_estimate <hostname> <filename>"
  exit
fi

echo "Cleaning old size estimate results"
./clean_size_estimate_test

./run spark.examples.EstimateTextFile "$@" 2>$ERR_FILE 1>$OUT_FILE

pushd $MAT_DIR
./ParseHeapDump.sh $FWDIR/heap.bin org.eclipse.mat.api:top_components 2>/tmp/mat.err 1>/tmp/mat.out
popd

unzip heap_Top_Components.zip 2>/dev/null 1>/dev/null
MAT=`lynx -dump pages/*.html | grep BoundedMemoryCache | grep "%" | tail -1 | sed 's/,//g'`
echo $MAT

USED=`cat $ERR_FILE | grep "space used" | tail -1`
echo $USED

MAT_VAL=`echo $MAT | awk '{print $4}'`
USED_VAL=`echo $USED | awk '{print $NF}'`

echo "Difference = $(($MAT_VAL - $USED_VAL)) bytes"
